title: Garage Sale
description: Мобильная витрина объявлений
remote_theme: jekyll/minima
permalink: /posts/:title:output_ext
markdown: kramdown
exclude: [fetch_data.py, requirements.txt, .github]
url: "https://demansh.github.io"
baseurl: "/sell"
